#!/usr/bin/env php
<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This script must be run from the CLI.\n");
    exit(1);
}

defined('DS') or define('DS', DIRECTORY_SEPARATOR);
defined('WEBROOT') or define('WEBROOT', dirname(__FILE__, 1));

require_once WEBROOT . DS . 'vendor/autoload.php';

use Marwa\Framework\Application;
use Marwa\Framework\Console\ConsoleKernel;

$app = new Application(WEBROOT);
$app->boot();

/** @var ConsoleKernel $kernel */
$kernel = $app->make(ConsoleKernel::class);
exit($kernel->handle());
