#!/usr/bin/env php
<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This script must be run from the CLI.\n");
    exit(1);
}

defined('DS') or define('DS', DIRECTORY_SEPARATOR);
defined('WEBROOT') or define('WEBROOT', dirname(__FILE__, 1));

require_once WEBROOT . DS . 'vendor/autoload.php';

use Marwa\Framework\Application;
use Marwa\Framework\Console\ConsoleKernel;

$app = new Application(WEBROOT);
$_ENV['APP_CONFIG_CACHE'] = $app->basePath('storage/cache/config.php');
$_SERVER['APP_CONFIG_CACHE'] = $_ENV['APP_CONFIG_CACHE'];
putenv('APP_CONFIG_CACHE=' . $_ENV['APP_CONFIG_CACHE']);
$_ENV['APP_ROUTE_CACHE'] = $app->basePath('storage/cache/routes.php');
$_SERVER['APP_ROUTE_CACHE'] = $_ENV['APP_ROUTE_CACHE'];
putenv('APP_ROUTE_CACHE=' . $_ENV['APP_ROUTE_CACHE']);
$_ENV['APP_MODULE_CACHE'] = $app->basePath('storage/cache/modules.php');
$_SERVER['APP_MODULE_CACHE'] = $_ENV['APP_MODULE_CACHE'];
putenv('APP_MODULE_CACHE=' . $_ENV['APP_MODULE_CACHE']);
$app->boot();

/** @var ConsoleKernel $kernel */
$kernel = $app->make(ConsoleKernel::class);
exit($kernel->handle());
