services:
  php:
    build: ./php
    volumes:
      - ../:/var/www
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    command: >
      sh -c "
        chown -R www-data:www-data /var/www/storage &&
        chmod -R 775 /var/www/storage &&
        php-fpm
      "  
    depends_on:
      - mysql
    networks:
      - appnet
    env_file:
      - ../.env

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet
    env_file:
      - ../.env

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet
    env_file:
      - ../.env

  redis:
    image: redis:alpine
    networks:
      - appnet
    env_file:
      - ../.env

volumes:
  db_data:

networks:
  appnet:
